name: Build and push Docker image

on:
  push:
    tags:
      - "v*"

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build Docker image
    runs-on: ${{ matrix.builder }}
    strategy:
      fail-fast: false
      matrix:
        app: [smp-server, xftp-server]
        app_port: [5223, 443]
        arch: [amd64, arm64]
        builder: [buildjet-4vcpu-ubuntu-2204,buildjet-8vcpu-ubuntu-2204-arm]
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: registry.samipsolutions.fi
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.samipsolutions.fi/library/${{ matrix.app }}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}

      - name: Build Docker image
        run: |
          docker build --build-arg APP=${{ matrix.app }} --build-arg APP_PORT=${{ matrix.app_port }} -t ${{ steps.meta.outputs.tags }} --platform linux/${{ matrix.arch }} .
          docker push ${{ steps.meta.outputs.tags }}

  merge-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Harbor registry
        uses: docker/login-action@v2
        with:
          registry: registry.samipsolutions.fi
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Create and push multi-arch images
        run: |
          docker manifest create registry.samipsolutions.fi/library/smp-server:latest registry.samipsolutions.fi/library/smp-server:latest-amd64 registry.samipsolutions.fi/library/smp-server:latest-arm64
          docker manifest annotate registry.samipsolutions.fi/library/smp-server:latest registry.samipsolutions.fi/library/smp-server:latest-amd64 --arch amd64
          docker manifest annotate registry.samipsolutions.fi/library/smp-server:latest registry.samipsolutions.fi/library/smp-server:latest-arm64 --arch arm64
          docker manifest push registry.samipsolutions.fi/library/smp-server:latest

          docker manifest create registry.samipsolutions.fi/library/xftp-server:latest registry.samipsolutions.fi/library/xftp-server:latest-amd64 registry.samipsolutions.fi/library/xftp-server:latest-arm64
          docker manifest annotate registry.samipsolutions.fi/library/xftp-server:latest registry.samipsolutions.fi/library/xftp-server:latest-amd64 --arch amd64
          docker manifest annotate registry.samipsolutions.fi/library/xftp-server:latest registry.samipsolutions.fi/library/xftp-server:latest-arm64 --arch arm64
          docker manifest push registry.samipsolutions.fi/library/xftp-server:latest
